// <auto-generated />
namespace BorsaPortal.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddHistoricalPEAndPriceToSalesFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHistoricalPEAndPriceToSalesFields));

        string IMigrationMetadata.Id
        {
            get { return "202601211200000_AddHistoricalPEAndPriceToSalesFields"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
